# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
arr0 = np.zeros([1,10])
print(arr0)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Create an array of 10 ones

In [4]:
arr1 = np.ones([1,10])
print(arr1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### Create an array of 10 fives

In [5]:
arr1 = np.ones([1,10])
arr5 = 5 * arr1
print(arr5)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


#### Create an array of the integers from 10 to 50

In [16]:
def gen_arr(start,end):
  lst_int = []
  for i in range(start,end+1):
    lst_int.append(i)
  arr_int = np.array(lst_int)
  return arr_int

my_arr = gen_arr(10,50)
my_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [17]:
#Function that generates an array for the given range in Normal or even or odd modes:
def gen_arr(start,end,type = "Normal"):
  lst_int = []
  if (type == "Normal"):
    for i in range(start,end+1):
      lst_int.append(i)

  elif(type == "Even"):
    for i in range(start,end+1):
      if (i%2 == 0):
        lst_int.append(i)
      else:
        continue

  elif(type == "Odd"):
    for i in range(start,end+1):
      if (i%2 != 0):
        lst_int.append(i)
      else:
        continue
  else:
    print("Error : Unknown type")
    return

  arr_int = np.array(lst_int)
  return arr_int


#Trying the function
#Normal
norm_arr = gen_arr(10,50)
print(norm_arr)
#Even:
even_arr = gen_arr(10,50,"Even")
print(even_arr)
#Odd
odd_arr = gen_arr(10,50,"Odd")
print(odd_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
arr = gen_arr(0,8)
my_arr = arr.reshape([3,3])
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [22]:
import numpy as np
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [40]:
from numpy import random
ran_num = random.rand()
ran_num

0.4517870378165427

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [43]:
from numpy import random
ran_arr = random.standard_normal(25)
ran_arr

array([-1.10141969,  0.65732047,  2.91170082, -0.45256725,  0.16194552,
       -0.38460862,  1.07598128, -1.15566156,  0.08147872, -0.02089972,
        1.07486947,  0.21213314, -1.2185959 , -0.77149566, -1.92736565,
        0.10619123,  0.11207721,  0.53441074, -0.77310858, -1.06809537,
       -0.02649594, -0.43263197,  0.30015259, -1.5768403 ,  0.04089641])

#### Create the following matrix:

In [57]:
start , end , step  = 0.01 ,  1.00 , 0.01
float_arr = np.arange(start,end+step,step)
my_arr = float_arr.reshape([10,10])
my_arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [59]:
linspace_arr = np.linspace(0,1,20)
linspace_arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [61]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
my_mat = mat[2: , 1: ]
my_mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [65]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
value = mat[3,4]
value

20

20

In [67]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
col = mat[ :3 , 1 ]
req_col = col.reshape([3,1])
req_col

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [68]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
req_row = mat[4 , : ]
req_row

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [71]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
req_rows = mat[3:5 , : ]
req_rows

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [72]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [74]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [73]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!